Updated mission.sqm
Task-Force-Raider/Liberation-Livonia pull request #27
Opened 2019-11-24 11:06 UTC by the-pope-himself

1. Created custom default loadouts for Ronin
2. Shifted FOB-box to a safer location
3. Removed stamina and stamina bar

2019-11-25 03:47 UTC, Grewsome2018 commented
Resolve the conflicts before I approve pls xx

2019-11-25 03:56 UTC, Grewsome2018 commented
Fixes #16

2019-11-26 08:22 UTC, Grewsome2018 requested changes
Fix conflicts then resubmit for review

2019-11-26 10:54 UTC, BroBeansCPG approved these changes

2019-11-28 17:36 UTC, Grewsome2018 approved these changes

2019-11-28 17:36 UTC, merged